### PR TITLE
Add automatic updates of data

### PR DESCRIPTION
**Pull request by jtpotato**
Addresses #12 

Uses GitHub Actions to automatically run the script on the 1st of each month.

It should be noted that the year is listed as `YYYY` instead of `YYYY-MM-DD` in a few CSV files (affecting #8) .
I'm not familiar enough with bash script to change the format, although I could probably work it out when I have the time - kind of hoping that someone else already has a way of doing it though.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@jtpotato i think no problem we have year as pure `YYYY`.

**Comment by rufuspollock** [comment]
@jtpotato great job thank-you. Assume happy to license under public domain (not even sure any copyright in the contribution but good to check!) 🙏

**Comment by jtpotato** [comment]
> @jtpotato great job thank-you. Assume happy to license under public domain (not even sure any copyright in the contribution but good to check!) 🙏

yeah! I assumed it would go under Unlicense just like the rest of the project :)

**Comment by rufuspollock** [comment]
@jtpotato thanks so much for this 👏 really appreciated 🙏

**Pull request merged**
